# Wiki: https://mo-mi.gitbook.io/xiaomomi-plugins/

# Don't change this unless you are clear about what you are doing
# 请不要修改此项目，除非你明确你在做什么
config-version: '25'

# bStats
metrics: true

# Check for plugin updates
# It works asynchronously and would not cause lag
# 检查更新，异步进行，不会造成卡顿
update-checker: true

# You can create language files for your locale and use them
# You are welcomed to submit language files and become one of the contributors
# chinese/english/spanish/turkish
# 你可以自由创建语言文件并使用他们
lang: english

# Worlds where fishing mechanic takes effects
# 启用本插件的世界
worlds:
  # Mode: whitelist/blacklist
  # 模式：白名单/黑名单
  mode: whitelist
  list:
    - world
    - world_nether

# Mechanic settings
# 机制设置
mechanics:

  # Add CustomFishing NBT tags to the loots
  # Set it to false if you have problems with stacking
  # 为每个战利品增加特殊的CustomFishing NBT标签以被插件识别
  # 禁用此项目将会导致吃食物触发的动作失效
  add-custom-fishing-tags-to-loots: true

  # Disable the fishing bar totally
  # 关闭捕鱼条
  disable-bar-mechanic: false

  # The requirements for the plugin to work
  # This is designed for servers that want to enable the fishing mechanic at a specific time
  # 插件工作所需的条件，比如你希望在特殊事件才启用本插件的机制
  mechanic-requirements: {}

  # Does the fishing bar show up instantly when the fish is hooked
  # In this mode, vanilla loots are not available unless you add them to the loot system!
  # 是否在鱼咬钩后立刻显示捕鱼条，而不是需要右键后才显示
  # 注意：启用本设置会导致无法获取原版钓鱼战利品
  instant-bar: false

  # other loots
  # 其他战利品
  other-loots:

    # Vanilla loots
    # 原版战利品
    vanilla:
      enable: true
      # 0.4 indicates that 40% of the loots are vanilla white the rest are from CustomFishing Loot system
      # If there's no custom loot, it would definitely be a vanilla loot
      # 0.4代表40%的战利品来自于原版，60%来自CustomFishing物品库
      # 如果钓鱼的地方没有自定义战利品，那么下一个一定是原版战利品
      ratio: 0.4

    # mcMMO loots
    # mcMMO战利品
    mcMMO:
      # mcMMO treasure system
      # Chance represents the opportunity to **try** and become a treasure of mcMMO
      # mcMMO宝藏系统
      # 概率代表尝试变成mcMMO宝藏的概率，但这不意味着50%概率一定会变成mcMMO宝藏
      enable: false
      chance: 0.5

  # Does the special fishing mechanic requires special rod
  # 是否需要特殊鱼竿才能体验钓鱼机制
  need-special-rod-to-fish: false

  # Does the CustomFishing loots requires special rod
  # 是否需要特殊鱼竿才能获取钓鱼插件物品库的内容
  need-special-rod-for-loots: false

  # Do all the rods have the ability to fish in lava
  # 任何鱼竿都能在岩浆中钓鱼吗
  all-rods-fish-in-lava: false

  # Does rod lose durability when player successfully fish
  # 钓鱼成功后是否消耗耐久度
  rod-lose-durability: true

  # Competition
  # 钓鱼比赛
  fishing-competition:
    enable: true
    # Enable redis server to sync data between servers
    # 启用Redis服务器以跨服同步比赛数据
    redis: false

  # Fishing bag is a place where players can store their baits, utils, rods (Fish optional)
  # 渔具袋是玩家存放鱼饵，实用道具，鱼竿的地方，其中的鱼饵会在钓鱼时被消耗
  fishing-bag:
    enable: true
    # Fishing bag window title
    # 渔具袋的容器标题
    bag-title: '<blue>{player}''s Fishing Bag'
    # Can fishing bag store the loots? (Requires add-custom-fishing-tags-to-loots: true)
    # 渔具袋是否能存储钓鱼战利品(需要设置add-custom-fishing-tags-to-loots: true)
    can-store-loot: false
    # Other whitelist-items
    # 允许放入渔具袋的其他物品白名单
    whitelist-items:
      - fishing_rod

  # Lava fishing settings
  # 岩浆钓鱼设置
  lava-fishing:
    # ticks
    min-wait-time: 100
    max-wait-time: 600

  # Splash effect when the bobber falls into water
  # 鱼钩落水时的水花飞溅效果
  splash-animation:
    water:
      enable: true
      # config the item in utils
      item: water_effect
      # ticks
      time: 25
    lava:
      enable: true
      item: lava_effect
      # ticks
      time: 25

  # Record the statistics of player's fishing results
  # 记录玩家的捕鱼数据
  fishing-statistics:
    enable: true

  # enable bait animation
  # 启用抛出诱饵的动画
  bait-animation: true

# Titles
# 标题设置
titles:
  success:
    enable: true
    title:
      - '<green>GG!</green>'
      - '<green>Good Job!</green>'
    subtitle:
      - 'You caught a {loot}'
      - 'Whoa! Nice catch!'
      - 'Oh {loot} here we go!'
      - 'Let''s see what it is!'
    fade:
      # ticks
      in: 10
      stay: 30
      out: 10
  failure:
    enable: true
    title:
      - '<red>Be concentrated!</red>'
      - '<red>What a pity!</red>'
      - '<red>Try next time!</red>'
      - '<red>Bad luck</red>'
    subtitle:
      - 'The fish escaped...'
    fade:
      in: 10
      stay: 30
      out: 10

# Other settings
# 其他设置
other-settings:

  # Thread pool settings
  # 线程池设置
  thread-pool-settings:
    # The size of the core Thread pool, that is, the size of the Thread pool when there is no task to execute
    # Increase the size of corePoolSize when you are running a large server with many players fishing at the same time
    # 核心线程池大小，即在没有任务需要执行的时候线程池的大小
    corePoolSize: 4
    # The maximum number of threads allowed to be created in the Thread pool. The current number of threads in the Thread pool will not exceed this value
    # 线程池中允许创建的最大线程数，线程池中的当前线程数目不会超过该值
    maximumPoolSize: 8
    # If a thread is idle for more than this attribute value, it will exit due to timeout
    # 如果一个线程处在空闲状态的时间超过了该属性值，就会因为超时而退出（秒）
    keepAliveTime: 10

  # Hide the data saving information
  # 隐藏数据保存日志
  hide-data-saving-info: false

  # date format in {date} placeholder
  # {date}变量的格式
  date-format: 'yyyy-MM-dd'

  # Event priority: MONITOR HIGHEST HIGH NORMAL LOW LOWEST
  # 事件优先级
  event-priority: NORMAL

  # If enabled, players would not be able to get job exp in vanilla way
  # 如果启用，玩家则无法通过原版方式获得Jobs经验
  disable-JobsReborn-fishing-exp: false

  # Convert MMOItems' rod into CustomFishing's rod (Plz use capital letters otherwise it would not be converted)
  # keep the same key name both in MMOItems and CustomFishing so rods can inherit the bonus of those in CustomFishing
  # 将MMOItems中的鱼竿转换为CustomFishing的鱼竿，只需要保持相同的键名即可继承效果
  convert-MMOItems-rods: false

  # Prevent other players to pick up your fishing loot
  # This is useful for players to fish in a public area
  # 防止其他玩家抢夺捕鱼战利品
  prevent-other-players-pick-up-loot: false

  # Log the earnings of fish on the console
  # 后台记录玩家销售鱼类所得金额
  log-earnings: true

  # Set the MMOCore profession name
  # MMOCore职业名
  MMOCore-profession-name: 'customfishing'

  # Set the offset characters' unicodes
  # 设置左右偏移字符的unicode
  offset-characters:
    font: customfishing:offset_chars
    '1': 
    '2': 
    '4': 
    '8': 
    '16': 
    '32': 
    '64': 
    '128': 
    '-1': 
    '-2': 
    '-4': 
    '-8': 
    '-16': 
    '-32': 
    '-64': 
    '-128': 