###############
# Game Type 1 #
###############
rainbow_1:
  game-type: 1
  title: '<#B22222>RED!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀋'
    pointer: '뀁'
  arguments:
    pointer-offset: -119
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 1
    2: 0
    3: 0
    4: 0
    5: 0
    6: 0
    7: 0
rainbow_2:
  game-type: 1
  title: '<#FFA500>ORANGE!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀋'
    pointer: '뀁'
  arguments:
    pointer-offset: -119
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 0
    2: 1
    3: 0
    4: 0
    5: 0
    6: 0
    7: 0
rainbow_3:
  game-type: 1
  title: '<#FFFF00>YELLOW!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀋'
    pointer: '뀁'
  arguments:
    pointer-offset: -119
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 0
    2: 0
    3: 1
    4: 0
    5: 0
    6: 0
    7: 0
rainbow_4:
  game-type: 1
  title: '<GREEN>GREEN!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀋'
    pointer: '뀁'
  arguments:
    pointer-offset: -119
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 0
    2: 0
    3: 0
    4: 1
    5: 0
    6: 0
    7: 0
rainbow_5:
  game-type: 1
  title: '<#00FFFF>AQUA!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀋'
    pointer: '뀁'
  arguments:
    pointer-offset: -119
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 1
    6: 0
    7: 0
rainbow_6:
  game-type: 1
  title: '<#1E90FF>BLUE!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀋'
    pointer: '뀁'
  arguments:
    pointer-offset: -119
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
    6: 1
    7: 0
rainbow_7:
  game-type: 1
  title: '<#9400D3>PURPLE!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀋'
    pointer: '뀁'
  arguments:
    pointer-offset: -119
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
    6: 0
    7: 1
bar_1:
  game-type: 1
  title:
    - 'So close, stay cool!'
    - 'The fish is hooked, focus on it!'
    - 'Sturdy on! Victory is almost ours!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀂'
    pointer: '뀁'
  arguments:
    pointer-offset: -183
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 0
    2: 0
    3: 0
    4: 0.2
    5: 0.6
    6: 1
    7: 0.6
    8: 0.2
    9: 0
    10: 0
    11: 0
bar_2:
  game-type: 1
  title:
    - 'So close, stay cool!'
    - 'The fish is hooked, focus on it!'
    - 'Sturdy on! Victory is almost ours!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀃'
    pointer: '뀁'
  arguments:
    pointer-offset: -183
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 0
    2: 0.2
    3: 0.6
    4: 1
    5: 0.6
    6: 0.2
    7: 0
    8: 0
    9: 0
    10: 0
    11: 0
bar_3:
  game-type: 1
  title:
    - 'So close, stay cool!'
    - 'The fish is hooked, focus on it!'
    - 'Sturdy on! Victory is almost ours!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀄'
    pointer: '뀁'
  arguments:
    pointer-offset: -183
    pointer-width: 5
    width-per-section: 16
  success-rate-sections:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
    6: 0.2
    7: 0.6
    8: 1
    9: 0.6
    10: 0.2
    11: 0
bar_4:
  game-type: 1
  title:
    - 'So close, stay cool!'
    - 'The fish is hooked, focus on it!'
    - 'Sturdy on! Victory is almost ours!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀅'
    pointer: '뀁'
  arguments:
    pointer-offset: -183
    pointer-width: 5
    width-per-section: 8
  success-rate-sections:
    1: 0
    2: 0
    3: 0.1
    4: 0.1
    5: 0
    6: 0
    7: 0.2
    8: 0.2
    9: 0.6
    10: 0.6
    11: 1
    12: 0.6
    13: 0.2
    14: 0
    15: 0.2
    16: 0.6
    17: 1
    18: 0.6
    19: 0.2
    20: 0.1
    21: 0
    22: 0
bar_5:
  game-type: 1
  title:
    - 'So close, stay cool!'
    - 'The fish is hooked, focus on it!'
    - 'Sturdy on! Victory is almost ours!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀆'
    pointer: '뀁'
  arguments:
    pointer-offset: -183
    pointer-width: 5
    width-per-section: 8
  success-rate-sections:
    1: 1
    2: 0
    3: 0.1
    4: 0.2
    5: 0.2
    6: 0.6
    7: 0.6
    8: 1
    9: 0.6
    10: 0.2
    11: 0
    12: 0.2
    13: 0.6
    14: 1
    15: 0.6
    16: 0.2
    17: 0
    18: 1
    19: 0.2
    20: 0.1
    21: 0
    22: 0
bar_6:
  game-type: 1
  title:
    - 'So close, stay cool!'
    - 'The fish is hooked, focus on it!'
    - 'Sturdy on! Victory is almost ours!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀇'
    pointer: '뀁'
  arguments:
    pointer-offset: -183
    pointer-width: 5
    width-per-section: 8
  success-rate-sections:
    1: 0.1
    2: 0.1
    3: 0.1
    4: 0.1
    5: 0.1
    6: 0.1
    7: 0.1
    8: 0.1
    9: 1
    10: 0
    11: 1
    12: 0
    13: 1
    14: 0
    15: 0.1
    16: 0.1
    17: 0.1
    18: 0.1
    19: 0.1
    20: 0.1
    21: 0.1
    22: 0.1
bar_7:
  game-type: 1
  title:
    - 'So close, stay cool!'
    - 'The fish is hooked, focus on it!'
    - 'Sturdy on! Victory is almost ours!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀈'
    pointer: '뀁'
  arguments:
    pointer-offset: -183
    pointer-width: 5
    width-per-section: 4
  success-rate-sections:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
    6: 0
    7: 0
    8: 0
    9: 0
    10: 0
    11: 0
    12: 0
    13: 0
    14: 0
    15: 0
    16: 0
    17: 0
    18: 0
    19: 0
    20: 0
    21: 0
    22: 0
    23: 0
    24: 0
    25: 0
    26: 0
    27: 0
    28: 0
    29: 0
    30: 0
    31: 0
    32: 0
    33: 0
    34: 0
    35: 0.1
    36: 0.1
    37: 0
    38: 0
    39: 1
    40: 0
    41: 0
    42: 0.3
    43: 0.3
    44: 0.3
bar_8:
  game-type: 1
  title:
    - 'So close, stay cool!'
    - 'The fish is hooked, focus on it!'
    - 'Sturdy on! Victory is almost ours!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀉'
    pointer: '뀁'
  arguments:
    pointer-offset: -183
    pointer-width: 5
    width-per-section: 4
  success-rate-sections:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
    6: 0
    7: 0
    8: 0
    9: 0
    10: 0
    11: 0
    12: 0
    13: 0
    14: 0
    15: 0
    16: 0
    17: 0.2
    18: 0.2
    19: 0.2
    20: 0.6
    21: 1
    22: 0.6
    23: 0.2
    24: 0.2
    25: 0.2
    26: 0.2
    27: 0
    28: 0
    29: 0
    30: 0
    31: 0
    32: 0
    33: 0
    34: 0
    35: 0
    36: 0
    37: 0
    38: 0
    39: 0
    40: 0
    41: 0
    42: 0
    43: 0
    44: 0
bar_9:
  game-type: 1
  title:
    - 'So close, stay cool!'
    - 'The fish is hooked, focus on it!'
    - 'Sturdy on! Victory is almost ours!'
  subtitle:
    font: 'customfishing:default'
    bar: '뀊'
    pointer: '뀁'
  arguments:
    pointer-offset: -183
    pointer-width: 5
    width-per-section: 4
  success-rate-sections:
    1: 1
    2: 0
    3: 0
    4: 0
    5: 0
    6: 0
    7: 0
    8: 0
    9: 0
    10: 0
    11: 0
    12: 0
    13: 0
    14: 0
    15: 0
    16: 0
    17: 0
    18: 0
    19: 0
    20: 0
    21: 0
    22: 0
    23: 0
    24: 0
    25: 0
    26: 0
    27: 0
    28: 0
    29: 0
    30: 0
    31: 0
    32: 0
    33: 0
    34: 0
    35: 0
    36: 0
    37: 0
    38: 0
    39: 0
    40: 0
    41: 0
    42: 0
    43: 0
    44: 1

###############
# Game Type 2 #
###############
bar_10:
  game-type: 2
  title: '{progress}'
  # Tip would show on the title to guide the player how to play
  tip: '<gray>Press <red><key:key.sneak> <gray>to start'
  subtitle:
    font: 'customfishing:default'
    bar: '뀌'
    judgment-area: '뀍'
    fish: '뀎'
  arguments:
    punishment: 0.2
    bar-effective-area-width: 155
    judgment-area-offset: -160
    judgment-area-width: 33
    fish-icon-width: 8
    water-resistance: 0.15
    pulling-strength: 0.35
    loosening-strength-loss: 0.25
  hold-time-requirements:
    - 2
    - 2
    - 3
    - 3
    - 4
  progress:
    - '<font:customfishing:icons>뀁</font>'
    - '<font:customfishing:icons>뀂</font>'
    - '<font:customfishing:icons>뀃</font>'
    - '<font:customfishing:icons>뀄</font>'
    - '<font:customfishing:icons>뀅</font>'
    - '<font:customfishing:icons>뀆</font>'
    - '<font:customfishing:icons>뀇</font>'
    - '<font:customfishing:icons>뀈</font>'
    - '<font:customfishing:icons>뀉</font>'

###############
# Game Type 3 #
###############
bar_11:
  game-type: 3
  title: '{strain}'
  # Tip would show on the title to guide the player how to play
  tip: '<gray>Press <red><key:key.sneak> <gray>to start'
  subtitle:
    font: 'customfishing:default'
    bar: '뀓'
    fish: '뀎'
    struggling-fish:
      - 뀑
      - 뀐
      - 뀑
      - 뀒
  arguments:
    bar-effective-area-width: 218
    fish-offset: -221
    fish-start-position: 165
    fish-icon-width: 8
    success-position: 21
    ultimate-strain: 50
    normal-pull-strain-increase: 1
    struggling-strain-increase: 2
    loosening-strain-loss: 2
  strain:
    - '<font:customfishing:icons>뀑</font>'
    - '<font:customfishing:icons>뀒</font>'
    - '<font:customfishing:icons>뀓</font>'
    - '<font:customfishing:icons>뀔</font>'
    - '<font:customfishing:icons>뀕</font>'
    - '<font:customfishing:icons>뀖</font>'
    - '<font:customfishing:icons>뀗</font>'
    - '<font:customfishing:icons>뀘</font>'
    - '<font:customfishing:icons>뀙</font>'